apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          # cluster generator, 'child' #2
          - git:
              repoURL: https://github.com/umairishaq/argo-managed-apps.git
              revision: HEAD
              files:
                - path: multi-target/clusters/*.json
          - git:
              repoURL: https://github.com/umairishaq/argo-managed-apps.git
              revision: HEAD
              directories:
                - path: multi-target/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path.basename}}'
      source:
        repoURL: https://github.com/umairishaq/argo-managed-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{cluster.address}}'
        namespace: '{{path.basename}}'