apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-cluster-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/umairishaq/argo-managed-apps.git
        revision: HEAD
        files:
        - path: "multi-target/clusters/*.json"
  template:
    metadata:
      name: '{{cluster.name}}-app-of-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/umairishaq/argo-managed-apps.git
        targetRevision: HEAD
        path: 'multi-target/apps/'
        directory:
          recurse: true
      destination:
        server: '{{cluster.address}}'